### ISSUE TITLE
[Feature] Visualization of tracking results

### ISSUE THREAD

**Issue by IkumaUchida** [AtomScott/SoccerTrack#28]
### Search before asking

- [ ] I have searched the SoccerTrack [issues](https://github.com/AtomScott/SoccerTrack/issues) and found no similar feature requests.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!
---
_If you are willing to submit a PR, please do the following._

- [ ] I have discussed the requested feature's details with core devs.
- [ ] I have made a Pull Request (or draft PR).
- [ ] I have linked the PR to this issue.

**Comment by IkumaUchida** [comment]
### 実装方針
* 実装の概要
トラッキング用評価用スクリプトを参考とし、soccertrackの物体検出/モジュールから出力されたcamera detaframeを使用し、物体検出の精度を算出するための仕組みを作成する。

参考コードは以下の通り
- [py-motmetrics](https://github.com/cheind/py-motmetrics)
- [TrackEval](https://github.com/JonathonLuiten/TrackEval)

### 1. camera dataframeを作成
- camera dataframeは以下の構成とする。
    - level 1 - teamid 
    - level 2 - playerid 
    - level 3
        - px - ピッチ座標 X 
        - py - ピッチ座標 Y      
        - bbox_x1 
        - bbox_x2 
        - bbox_y1 
        - bbox_y2 

**現段階のデータセットに関する不明点**
- [ ]  推論時にidが増えてしまう場合のデータセット形について

### 2. トラッキングの評価指標について


```python
gt_df = ... # ファイルから読み込み
bbox_df = ... # 推論結果

from soccertrack.metrics import hota_score
hota_score(gt_df, bbox_df)
>>> 0.69 # HOTAのスコア
or
>>> 
"""
         IDF1   IDP   IDR  Rcll  Prcn GT MT PT ML FP FN IDs  FM  MOTA  MOTP
full    83.3% 83.3% 83.3% 83.3% 83.3%  2  1  1  0  1  1   1   1 50.0% 0.340
part    75.0% 75.0% 75.0% 75.0% 75.0%  2  1  1  0  1  1   0   0 50.0% 0.167
OVERALL 80.0% 80.0% 80.0% 80.0% 80.0%  4  2  2  0  2  2   1   1 50.0% 0.275
"""
 # 各サブメトリごとに出力(上記はCLEAR MOTの例、HOTAの場合は別のサブメトリクスがある)
```

**Comment by pushkin-dev** [comment]
Inference on a single frame

When I importing the package 
from soccertrack import detection_model
Run....

Output:
      from soccertrack import detection_model
      from soccertrack.utils import get_git_root
     # let's load the first frame of the video

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/soccertrack/detection_model/__init__.py:1
----> 1 from soccertrack.detection_model.base import BaseDetectionModel
      2 from soccertrack.logger import logger
      4 from soccertrack.detection_model.yolov5 import YOLOv5, YOLOv5n, YOLOv5s, YOLOv5m, YOLOv5l, YOLOv5x

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/soccertrack/detection_model/base.py:10
      8 from soccertrack.logger import logger
      9 from soccertrack.types import Detection
---> 10 from soccertrack.types.detection import Detection
     11 from soccertrack.types.detections import Detections
     12 from soccertrack.utils import read_image

ModuleNotFoundError: No module named 'soccertrack.types.detection'; 'soccertrack.types' is not a package

---
how to fix this?
thank you in advance
